/* Char_3A.h - Colon Character
 *
 * D Provine, 20 Mar 2012
 * Edited: Will Graham
 *
 * $Id: $
 */

const byte Char_3A[10] = {
    0x00,     // ........
    0x00,     // ........
    0x1f,     // ...XX...
    0x1f,     // ...XX...
    0x00,     // ........
    0x00,     // ........
    0x1f,     // ...XX...
    0x1f,     // ...XX...
    0x00,     // ........
    0x00      // ........
};

