# Makefile for abprint

PROGRAM = showchars
SOURCES = showchars.c
OBJECTS = showchars.o
CFLAGS  = -O

.SUFFIXES:
.SUFFIXES: .c .o

.c.o : ; cc $(CFLAGS) -c $< 

$(PROGRAM) : $(OBJECTS)
	cc -o $@ $(CFLAGS) $(OBJECTS)

clean: ; /bin/rm -f $(PROGRAM) $(OBJECTS)

depend : $(SOURCES)
	makedepend $(SOURCES) -I/usr/include/linux -I/usr/lib/gcc/x86_64-redhat-linux/3.4.6/include




# DO NOT DELETE

showchars.o: /usr/include/stdio.h /usr/include/features.h
showchars.o: /usr/include/stdc-predef.h /usr/include/sys/cdefs.h
showchars.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
showchars.o: /usr/include/linux/stddef.h /usr/include/bits/types.h
showchars.o: /usr/include/bits/typesizes.h /usr/include/libio.h
showchars.o: /usr/include/_G_config.h /usr/include/wchar.h
showchars.o: /usr/lib/gcc/x86_64-redhat-linux/3.4.6/include/stdarg.h
showchars.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
showchars.o: /usr/include/stdlib.h /usr/include/sys/types.h
showchars.o: /usr/include/linux/time.h /usr/include/linux/types.h
showchars.o: /usr/include/asm/types.h /usr/include/asm-generic/types.h
showchars.o: /usr/include/asm-generic/int-ll64.h
showchars.o: /usr/include/asm/bitsperlong.h
showchars.o: /usr/include/asm-generic/bitsperlong.h
showchars.o: /usr/include/linux/posix_types.h /usr/include/linux/stddef.h
showchars.o: /usr/include/asm/posix_types.h /usr/include/asm/posix_types_64.h
showchars.o: /usr/include/asm-generic/posix_types.h /usr/include/endian.h
showchars.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
showchars.o: /usr/include/bits/byteswap-16.h /usr/include/sys/select.h
showchars.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
showchars.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
showchars.o: /usr/include/alloca.h /usr/include/bits/stdlib-float.h
showchars.o: /usr/include/linux/string.h Chars/All_Chars.h Chars/Char_20.h
showchars.o: Chars/Char_21.h Chars/Char_22.h Chars/Char_23.h Chars/Char_24.h
showchars.o: Chars/Char_25.h Chars/Char_26.h Chars/Char_27.h Chars/Char_28.h
showchars.o: Chars/Char_29.h Chars/Char_2A.h Chars/Char_2B.h Chars/Char_2C.h
showchars.o: Chars/Char_2D.h Chars/Char_2E.h Chars/Char_2F.h Chars/Char_30.h
showchars.o: Chars/Char_31.h Chars/Char_32.h Chars/Char_33.h Chars/Char_34.h
showchars.o: Chars/Char_35.h Chars/Char_36.h Chars/Char_37.h Chars/Char_38.h
showchars.o: Chars/Char_39.h Chars/Char_3A.h Chars/Char_3B.h Chars/Char_3C.h
showchars.o: Chars/Char_3D.h Chars/Char_3E.h Chars/Char_3F.h Chars/Char_40.h
showchars.o: Chars/Char_41.h Chars/Char_42.h Chars/Char_43.h Chars/Char_44.h
showchars.o: Chars/Char_45.h Chars/Char_46.h Chars/Char_47.h Chars/Char_48.h
showchars.o: Chars/Char_49.h Chars/Char_4A.h Chars/Char_4B.h Chars/Char_4C.h
showchars.o: Chars/Char_4D.h Chars/Char_4E.h Chars/Char_4F.h Chars/Char_50.h
showchars.o: Chars/Char_51.h Chars/Char_52.h Chars/Char_53.h Chars/Char_54.h
showchars.o: Chars/Char_55.h Chars/Char_56.h Chars/Char_57.h Chars/Char_58.h
showchars.o: Chars/Char_59.h Chars/Char_5A.h Chars/Char_5B.h Chars/Char_5C.h
showchars.o: Chars/Char_5D.h Chars/Char_5E.h Chars/Char_5F.h Chars/Char_60.h
showchars.o: Chars/Char_61.h Chars/Char_62.h Chars/Char_63.h Chars/Char_64.h
showchars.o: Chars/Char_65.h Chars/Char_66.h Chars/Char_67.h Chars/Char_68.h
showchars.o: Chars/Char_69.h Chars/Char_6A.h Chars/Char_6B.h Chars/Char_6C.h
showchars.o: Chars/Char_6D.h Chars/Char_6E.h Chars/Char_6F.h Chars/Char_70.h
showchars.o: Chars/Char_71.h Chars/Char_72.h Chars/Char_73.h Chars/Char_74.h
showchars.o: Chars/Char_75.h Chars/Char_76.h Chars/Char_77.h Chars/Char_78.h
showchars.o: Chars/Char_79.h Chars/Char_7A.h Chars/Char_7B.h Chars/Char_7C.h
showchars.o: Chars/Char_7D.h Chars/Char_7E.h
